import uuid
import os
from dateutil import parser
from datetime import timezone

# fixed namespace for generating UUID v5 to ensure consistency of review_id across different runs and environments.
APP_NAMESPACE = uuid.UUID(os.getenv("UUID_STRING")) 

def generate_uuid_v5(source_id, source):
    """
    Generate UUID v5 from source and source_id.
    We can't save uuid.UUID type to BigQuery, so we convert it to string.

    Parameters
    ----------
    source_id : str
        Source ID (e.g., review ID from the original source)
    source : str
        Source of the review (e.g., tripadvisor,booking.com etc.)

    Returns
    -------
    review_id : str
        Generated UUID v5 as a string

    """

    return str(uuid.uuid5(APP_NAMESPACE, f"{source}|{source_id}"))



def add_review_id(reviews):
    """
    Add review_id to each review in reviews. review_id is generated by UUID v5 using source and source_id.
    """


    for review in reviews:
        if not review.get("source_id") or not review.get("source"):
            continue
        review["review_id"] = generate_uuid_v5(review.get("source_id"), review.get("source"))


    return reviews


def split_reviews_by_validity(validated_reviews):
    """ Split reviews into valid and invalid reviews based on 'is_valid' key in each review."""
       

    valid_reviews = []  # valid reviews for next steps
    invalid_reviews = []
    for review in validated_reviews:
        if review['is_valid']:
            valid_reviews.append(review)
        else:
            review.update({'tokens': []}) # add empty tokens for invalid reviews to keep the same schema as valid reviews
            invalid_reviews.append(review)

    return valid_reviews, invalid_reviews



def to_iso_utc(reviews):
    """ Convert posted_at to ISO format in UTC timezone. If posted_at is invalid, set posted_at_iso as None.

    examples:
    ******
    to_iso_utc("")              # None
    to_iso_utc("   ")           # None
    to_iso_utc(None)            # None
    to_iso_utc(12345)           # None
    to_iso_utc("invalid date")  # None
    to_iso_utc("2026-02-21")    # 2026-02-21T00:00:00Z
    ******
    """

    for review in reviews:
        s = review.get('posted_at')

        # None check and type check
        if not isinstance(s, str):
            review['posted_at_iso'] = None
            continue

        # Empty string check
        if not s.strip():
            review['posted_at_iso'] = None
            continue

        try:
            dt = parser.parse(s)

            # if timezone info is missing, assume it's in UTC
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)

            # Normalize to UTC
            dt = dt.astimezone(timezone.utc)

            review['posted_at_iso'] = dt.isoformat()

        except (ValueError, OverflowError, TypeError):
            review['posted_at_iso'] = None

    return reviews
